routes/web.php
<?php


/*
 * Admin Routes
 */
Route::prefix('admin')->group(function() {

    Route::middleware('auth:admin')->group(function() {
        // Dashboard
        Route::get('/', 'DashboardController@index');

        // Products
        Route::resource('/products','ProductController');
        Route::resource('/categories','CategoryController');

        // Orders
        Route::resource('/orders','OrderController');
        Route::get('/confirm/{id}','OrderController@confirm')->name('order.confirm');
        Route::get('/pending/{id}','OrderController@pending')->name('order.pending');

        // Users
        Route::resource('/users','UsersController');

        // Logout
        Route::get('/logout','AdminUserController@logout');

    });

    // Admin Login
    Route::get('/login', 'AdminUserController@index');
    Route::post('/login', 'AdminUserController@store');
});

/*
 * Front Routes
 */

Route::get('/', 'Front\HomeController@index')->name('home');
Route::get('/about', 'Front\HomeController@about')->name('about');
Route::get('/products', 'Front\HomeController@product')->name('product');
Route::post('/search', 'Front\HomeController@Search')->name('search');
Route::get('/filter/{id}', 'Front\HomeController@filter')->name('filter');

// User Registration
Route::get('/user/register','Front\RegistrationController@index');
Route::post('/user/register','Front\RegistrationController@store');

// User Login
Route::get('/user/login','Front\SessionsController@index');
Route::post('/user/login','Front\SessionsController@store');

// Logout
Route::get('/user/logout','Front\SessionsController@logout');

Route::get('/user/profile', 'Front\UserProfileController@index');
Route::get('/user/order/{id}','Front\UserProfileController@show');
Route::get('/user/edit/{id}','Front\UserProfileController@edit')->name('edit-profile');
Route::post('/user/update','Front\UserProfileController@update')->name('update-profile');
Route::post('/user/order/verify/{id}','Front\UserProfileController@verifyPayment')->name('verify');

// Cart
Route::get('/cart', 'Front\CartController@index');
Route::post('/cart','Front\CartController@store')->name('cart');
Route::patch('/cart/update/{product}','Front\CartController@update')->name('cart.update');
Route::delete('/cart/remove/{product}','Front\CartController@destroy')->name('cart.destroy');
Route::post('/cart/saveLater/{product}', 'Front\CartController@saveLater')->name('cart.saveLater');


// Save for later
Route::delete('/saveLater/destroy/{product}','Front\SaveLaterController@destroy')->name('saveLater.destroy');
Route::post('/cart/moveToCart/{product}','Front\SaveLaterController@moveToCart')->name('moveToCart');

// Checkout
Route::get('/checkout','Front\CheckoutController@index');
Route::post('/checkout','Front\CheckoutController@store')->name('checkout');

Route::get('empty', function() {
    Cart::instance('default')->destroy();
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
class CategoryController extends Controller
{
    public function index() {

        $categories = Category::all();

        return view('admin.categories.index', compact('categories'));
    }

    public function create() {
        $category = new Category();
        return view('admin.categories.create', compact('category'));
    }

    public function store(Request $request) {

        // Validate the form
        $request->validate([
           'name' => 'required',
            'description' => 'required',
            'image' => 'image|required'
        ]);

        // Upload the image
        if ($request->hasFile('image')) {
            $image = $request->image;
            $image->move('uploads', $image->getClientOriginalName());
        }

        // Save the data into database
        Category::create([
            'name' => $request->name,
            'description' => $request->description,
            'image' => $request->image->getClientOriginalName()

        ]);

        // Sessions Message
        $request->session()->flash('msg','Your category has been added');

        // Redirect

        return redirect('admin/categories/create');

    }

    public function edit($id) {
        $category = Category::find($id);
        return view('admin.categories.edit', compact('category'));
    }

    public function update(Request $request, $id) {

        // Find the category
        $category = Category::find($id);

        // Validate The form
        $request->validate([
           'name' => 'required',
            'description' => 'required',
        ]);

        // Check if there is any image
        if ($request->hasFile('image')) {
            // Check if the old image exists inside folder
            if (file_exists(public_path('uploads/') . $category->image)) {
                unlink(public_path('uploads/') . $category->image);
            }

            // Upload the new image
            $image = $request->image;
            $image->move('uploads', $image->getClientOriginalName());

            $category->image = $request->image->getClientOriginalName();
        }

        // Updating the category
        $category->update([
           'name' => $request->name,
            'description' => $request->description,
            'image' => $category->image
        ]);

        // Store a message in session
        $request->session()->flash('msg', 'Category has been updated');

        // Redirect
        return redirect('admin/categories');

    }

    public function show($id) {
        $category = Category::find($id);
        return view('admin.categories.details', compact('category'));
    }

    public function destroy($id) {
        // Delete the category
        Category::destroy($id);

        // Store a message
        session()->flash('msg','Category has been deleted');

        // Redirect back
        return redirect('admin/categories');


    }
}

resources/views/admin/categories/_fields.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
    {{ Form::label('category_name', 'Nama Kategori') }}
    {{ Form::text('name',$category->name,['class'=>'form-control border-input','placeholder'=>'Permak']) }}
    <span class="text-danger">{{ $errors->has('name') ? $errors->first('name') : '' }}</span>
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
    {{ Form::label('description', 'Deskripsi ') }}
    {{ Form::textarea('description',$category->description,['class'=>'form-control border-input','placeholder'=>'Deskripsi singkat mengenai kategori']) }}
    <span class="text-danger">{{ $errors->has('description') ? $errors->first('description') : '' }}</span>
</div>

<div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
    {{ Form::label('file','Gambar Thumbnail') }}
    {{ Form::file('image', ['class'=>'form-control border-input', 'id' => 'image']) }}
    <div id="thumb-output"></div>
    <span class="text-danger">{{ $errors->has('image') ? $errors->first('description') : '' }}</span>
</div>

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')

@section('page')
    Tambah Kategori
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-10 col-md-10">
            @include('admin.layouts.message')
            <div class="card">
                <div class="header">
                    <h4 class="title">Tambah Kategori</h4>
                </div>

                <div class="content">
                    {!! Form::open(['url' => 'admin/categories', 'files'=>'true']) !!}
                    <div class="row">
                        <div class="col-md-12">

                            @include('admin.categories._fields')

                            <div class="form-group">
                                {{ Form::submit('Add Category', ['class'=>'btn btn-primary']) }}
                            </div>

                        </div>

                    </div>


                    <div class="clearfix"></div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/categories/details.blade.php
@extends('admin.layouts.master')

@section('page')
    Detail Kategori
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Detail Kategori</h4>
                    <p class="category">Detail kategori {{ $category->name }}</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <tbody>

                        <tr>
                            <th>ID</th>
                            <td>{{ $category->id }}</td>
                        </tr>

                        <tr>
                            <th>Nama</th>
                            <td>{{ $category->name }}</td>
                        </tr>

                        <tr>
                            <th>Deskripsi</th>
                            <td>{{ $category->description }}</td>
                        </tr>

                        <tr>
                            <th>Created At</th>
                            <td>{{ $category->created_at->diffForHumans() }}</td>
                        </tr>

                        <tr>
                            <th>Updated At</th>
                            <td>{{ $category->updated_at->diffForHumans() }}</td>
                        </tr>

                        <tr>
                            <th>Gambar</th>
                            <td><img src="{{ url('uploads') . '/'. $category->image}}" alt="" class="img-thumbnail" style="width: 100px;"></td>
                        </tr>

                        </tbody>

                    </table>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')

@section('page')
    Ubah Category
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-10 col-md-10">
            @include('admin.layouts.message')
            <div class="card">
                <div class="header">
                    <h4 class="title">Ubah Category</h4>
                </div>

                <div class="content">
                    {!! Form::open(['url' => ['admin/categories', $category->id], 'files'=>'true', 'method'=>'put']) !!}
                    <div class="row">
                        <div class="col-md-12">

                            @include('admin.categories._fields')

                            <div class="form-group">
                                {{ Form::submit('Update Category', ['class'=>'btn btn-primary']) }}
                            </div>

                        </div>

                    </div>


                    <div class="clearfix"></div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')

@section('page')
    Lihat Kategori
@endsection

@section('content')

    <div class="row">

        <div class="col-md-12">

            @include('admin.layouts.message')

            <div class="card">
                <div class="header">
                    <h4 class="title">Kategori</h4>
                    <p class="category">Semua dafta kategori layanan</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped" id="dt">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nama Kategori</th>
                            <th>Deskripsi Layanan</th>
                            <th>Gambar</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($categories as $category)
                            <tr>
                                <td>{{ $category->id }}</td>
                                <td>{{ $category->name }}</td>
                                <td>{{ $category->description }}</td>
                                <td><img src="{{ url('uploads').'/'. $category->image }}" alt="{{ $category->image }}" style="width:50px;" class="img-thumbnail"></td>
                                <td>

                                    {{ Form::open(['route' => ['categories.destroy', $category->id], 'method'=>'DELETE']) }}
                                        {{ Form::button('<span class="fa fa-trash"></span>', ['type'=>'submit','class'=>'btn btn-danger btn-sm','onclick'=>'return confirm("Are you sure you want to delete this?")'])  }}
                                        {{ link_to_route('categories.edit','', $category->id, ['class' => 'btn btn-info btn-sm ti-pencil']) }}
                                        {{ link_to_route('categories.show','', $category->id, ['class' => 'btn btn-primary btn-sm ti-list']) }}
                                    {{ Form::close() }}

                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div>


    </div>


@endsection